### ISSUE TITLE
-u argument not work

### ISSUE THREAD

**Issue by myhip** [atarantini/wpbf#35]
![20150730161924](https://cloud.githubusercontent.com/assets/10770661/8978686/f9a1eb66-36d6-11e5-9de1-31d8077039bb.png)
Hi, as the example shown in above pic, the -u argument cannot be passed to wpbf.py

**Comment by atarantini** [comment]
The `-u` parameter will try the supplied username (`Checking URL & username`) but if the username can't be verified (WordPress return that the username does not exists) it will be removed from the list of usernames to be used.

When the usernames list is empty, wpbf will try to enumerate users in order to create a list.
